### ISSUE TITLE
input_source URL_LAUNCHER returns NAKError

### ISSUE THREAD

**Issue by visioner76** [vgavro/samsung-mdc#4]
Hi, i have problem with change input source for my Samsung QB75R TV
my software version on TV: 255@10.66.107.185:1515 T-KTM2ELAKUC-2070.3

when i try to change to URL_LAUNCHER, i recieve below message

samsung-mdc 255@10.66.107.185:1515 input_source URL_LAUNCHER
255@10.66.107.185:1515 NAKError: Negative Acknowledgement [error_code 1]

for HDMI1 and MEDIA_MAGIC_INFO_S works correctly

samsung-mdc 255@10.66.107.185:1515 input_source HDMI1
255@10.66.107.185:1515 <INPUT_SOURCE_STATE.HDMI1:33>
samsung-mdc 255@10.66.107.185:1515 input_source MEDIA_MAGIC_INFO_S
255@10.66.107.185:1515 <INPUT_SOURCE_STATE.MEDIA_MAGIC_INFO_S:96>

what could be the reason?

**Comment by vgavro** [comment]
We also had errors on setting URL_LAUNCHER if magic info is configured. There is no way to resolve it on protocol level, because there is no extended error info on that, and strictly every model (or even firmware) can behave differently. So this is blackbox reverse-engineering problem that depends on tv, firmware, magic info configured (or not) on your tv, and so on. 
For my recommendations to debug such unexpected errors on samsung TV - see https://github.com/vgavro/samsung-mdc#nakerror
I'm pretty sure you will get everything working after factory reset in worst case (without enabling magic info), and you can debug what state is reason of this error after that.
But also keep in mind, that I'm not even sure that URL_LAUNCHER is supported on household tv models. Maybe this mode is only supporte Samsung Smart Signage Platform, idk.
